site_name: Sathish Kumar's Machine Learning and Data Science Learnings
site_description: Documentation for the Data Science and Machine Learning Course.
site_author: Sathish Kumar # Replace with your name
repo_url: https://github.com/sathishkumar19/Scaler-DSML-Course # Replace with your repo URL
repo_name: Data Science and Machine Learning Repo

nav:
  - Home: index.md
  - DataBases,SQL & BigQuery: 
    - Databases: 'Databases/db-sql-bigquery-index.md'
    - SQL : 'Databases/sql.md'
    - BigQuery: 'Databases/bigquery.md'
#  - Tableau and Excel: 'Foundational Concepts/Tableau and Excel/README.md'
  - Python Programming:
    - Beginner Python 1: 'Python/python1.md'
    - Intermediate Python 2: 'Python/python2.md'

#  - Data Analytics and Statistics:
#    - Data Analytics and Visualisation - Probability and Stats: 'Data Analytics and Statistics/Data Analytics and Visualisation - Probability and Stats/README.md'
#    - Product Analytics: 'Data Analytics and Statistics/Product Analytics/README.md'
#  - Machine Learning Fundamentals:
#    - Maths for ML: 'Machine Learning Fundamentals/Maths for ML/README.md'
#    - Intro to ML and NN: 'Machine Learning Fundamentals/Intro to ML and NN/README.md'
#  - Supervised Learning:
#    - Supervised Algorithms: 'Supervised Learning/Supervised Algorithms/README.md'
#    - Advanced Supervised Algorithms: 'Supervised Learning/Advanced Supervised Algorithms/README.md'
#  - Unsupervised Learning and Recommender Systems:
#    - Unsupervised and RecSys: 'Unsupervised Learning and Recommender Systems/Unsupervised and RecSys/README.md'
#  - Advanced Topics:
#    - MLOps: 'Advanced Topics/MLOps/README.md'
#    - Neural Networks: 'Advanced Topics/Neural Networks/README.md'
#    - Computer Vision: 'Advanced Topics/Computer Vision/README.md'
#    - Natural Language Processing: 'Advanced Topics/Natural Language Processing/README.md'
#  - Topics to Explore:
#    - DSA: 'Topics to Explore/DSA/README.md'
#    - Agentic AI: 'Topics to Explore/Agentic AI/README.md'
#    - Reinforcement Learning: 'Topics to Explore/Reinforcement Learning/README.md'

#theme:
#  name: material
#  palette:
#    - scheme: default
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
#    - scheme: slate
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode
#  features:
#    - navigation.tabs
#    - navigation.sections
#    - toc.integrate
#    - navigation.top
#    - search.suggest
#    - search.highlight
#    - content.tabs.link
#    - content.code.annotation
#    - content.code.copy

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: 'logos/sathish.jpg'
  favicon: 'favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

repo_name: Sathish Kumar Github Repo
repo_url: https://github.com/sathishkumar19/Scaler-DSML-Course
edit_uri: edit/main/docs/