# Site settings
title: Scaler DSML Course
email: sathishkumar19@gmail.com # Replace with your email
description: >- This Website contains about Scalar DSML Course # this means to ignore newlines until "baseurl:"
  A website for the Scaler Data Science and Machine Learning Course.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sathishkumar19.github.io/Scaler-DSML-Course" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sathishkumar19 # Replace with your GitHub username

# Build settings
theme: minima # You can change this to another Jekyll theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
